---
title: "datamerge"
author: "Olga Chyzh"
date: "Oct 22, 2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,message = FALSE,warning = FALSE,fig.cap = "...")
```
## Required datasets: 
1. ./Data/countryfiles/ --weather data
2. ./Data/globalterrorismdb.csv ---GTD data
3. ./Data/BAAD_1_Lethality_Data.tab ---BAAD data
4. drugdata.csv --- data on drug-trafficking and harvests 

## Load libraries:
```{r}
library(data.table)
library(tidyverse)
library(magrittr)
library(tools)
library(countrycode)
library(terr.paper) #Olga's custom library with helpful functions
library(lubridate)


```


## Weather data:
```{r}
myfiles<-list.files("./Data/countryfiles/")

agg_stations<-function(countryfiles) {
d<-read.table(paste0("./Data/countryfiles/",countryfiles), header=TRUE)
return(d)
}

weatherdata<-do.call(rbind,lapply(myfiles,agg_stations))
weatherdata<-weatherdata[!is.na(weatherdata$ave_precip_mo) | !is.na(weatherdata$ave_mo_t),]

#Add country names:
mynames<-read.csv("./Data/countrynames.csv", header=TRUE,  quote="'")
mynames<-mynames %>% unite(countryname,c("COUNTRY","X","X.1","X.2","X.3","X.4","X.5","X.6"), sep="") %>% mutate(countryname=toTitleCase(tolower(countryname)))
mynames

weatherdata<- weatherdata %>% left_join(mynames,by=c("fips"="FIPS"))
weatherdata$countryname[weatherdata$countryname=="Unitedkingdom"]<-"United Kingdom"
weatherdata$countryname[weatherdata$countryname=="Unitedstates"]<-"United States of America"
weatherdata$countryname[weatherdata$countryname=="Saudiarabia"]<-"Saudi Arabia"
weatherdata$countryname[weatherdata$countryname=="Centralafricanrepublic"]<-"Central African Republic"
weatherdata$countryname[weatherdata$countryname=="Dominicanrepublic"]<-"Dominican Republic"
weatherdata$countryname[weatherdata$countryname=="Koreanorth"]<-"North Korea"
weatherdata$countryname[weatherdata$countryname=="Southafrica"]<-"South Africa"
weatherdata<-weatherdata[!is.na(weatherdata$countryname),]
weatherdata$ccode<-countrycode(weatherdata$countryname,'country.name','cown', warn=FALSE)
weatherdata<-weatherdata[!is.na(weatherdata$ccode),]


#write.csv(weatherdata, "weatherdata.csv", row.names=FALSE)


```


#Merge GTD data with drug data:
```{r}
gtd<-fread("Data/globalterrorismdb.csv") %>% 
  filter(imonth!=0 & is.finite(imonth)) %>% 
  group_by(gname, iyear, imonth, attacktype1_txt) %>% 
  summarise(num_attacks=length(eventid), .groups="keep") %>% 
  ungroup() %>% 
  spread(attacktype1_txt, num_attacks) %>% 
  mutate(incident=1)

#BAAD merge
baad<- read_delim("Data/BAAD_1_Lethality_Data.tab", "\t", escape_double = FALSE, trim_ws = TRUE) %>% 
  mutate(country=cowmastercountry,ccode=masterccode) %>% 
  select(-cowmastercountry, -masterccode,-mastertccode3606)

#add GTD.gname variable to BAAD
baad$GTD.gname<-GTD_gname(baad,"group")

#join baad and GTD data
mydata<-left_join(baad,gtd,by=c("GTD.gname"="gname")) %>%
        filter(!is.na(incident)) %>% select(-group) %>%
        arrange(GTD.gname,iyear,imonth)


#Start with a blank group-month-year dataset:
gr_dates<-mydata %>% 
  select(GTD.gname, imonth, iyear) %>% 
  mutate(date=paste(imonth,"01",iyear, sep="/"))  %>% 
  mutate(date=as.Date(date, "%m/%d/%Y")) %>% 
  group_by(GTD.gname) %>% 
  summarise(first_moyr=min(date), last_moyr=max(date), .groups="keep") %>% 
  ungroup() 

gr_dates <- as.list(as.data.frame(t(gr_dates)))

mk_data<-function(gr_dates ) {
  gr_dates<-as.data.frame(gr_dates)
  group=gr_dates[1,1]
  st_date=as.Date(gr_dates[2,1])
  end_date=as.Date(gr_dates[3,1])
dates<-seq(st_date,end_date, by="month")
return(cbind.data.frame(GTD.gname=group,date=dates, entry_date=st_date))
}


myframe<-do.call(rbind,lapply(gr_dates,mk_data))
myframe %>% 
  mutate(month=month(date), year=year(date))  %>% 
  left_join(mydata, by=c("GTD.gname"="GTD.gname","month"="imonth", "year"="iyear")) %>% 
  mutate(incident=replace_na(incident, 0)) %>% 
  arrange(GTD.gname,year,month) -> mydata


#Open drug data:
drugdata<- read.csv("drugdata1.csv") %>% 
  filter(!is.na(Harvest1))
drugdata$traffic<-1

mydata<-mydata %>% 
          left_join(drugdata, by=c("GTD.gname"="GTDname")) %>% 
          group_by(GTD.gname) %>% 
          fill(GTD.gname,traffic,statespond,country,ccode,fatalities19982005,OrgAge,ordsize,terrStrong,degree,ContainRelig,ContainEthno,LeftNoReligEthno,PureRelig,PureEthno,ReligEthno,ContainRelig2,ContainEthno2,Islam, Harvest1, Harvest2,Harvest3,Harvest4) %>% 
          mutate(`Armed Assault`=replace_na(`Armed Assault`,0),
                 Assassination=replace_na(Assassination, 0),
                 `Bombing/Explosion`=replace_na(`Bombing/Explosion`, 0),
                 `Facility/Infrastructure Attack`=replace_na(`Facility/Infrastructure Attack`, 0),
                 Hijacking=replace_na(Hijacking, 0),
                 `Hostage Taking (Barricade Incident)`=replace_na(`Hostage Taking (Barricade Incident)`, 0),
                 `Hostage Taking (Kidnapping)`=replace_na(`Hostage Taking (Kidnapping)`, 0),
                 `Unarmed Assault`=replace_na(`Unarmed Assault`, 0),
                 Unknown=replace_na(Unknown, 0),
                 traffic=replace_na(traffic, 0),
                 num_attacks=`Armed Assault`+Assassination+`Bombing/Explosion`+`Facility/Infrastructure Attack`+Hijacking+`Hostage Taking (Barricade Incident)` +`Hostage Taking (Kidnapping)`+`Unarmed Assault`+Unknown
                 ) %>% 
          select(GTD.gname,year,month,traffic, everything()) %>%
  arrange(-traffic, GTD.gname,year,month)
```

Merge with weather data:
```{r}
weatherdata<-read.csv("weatherdata.csv", header=T) %>% select(-ccode)
mydata$Drug_origin[is.na(mydata$Drug_origin)]<-mydata$country[is.na(mydata$Drug_origin)]
mydata<-mydata %>% left_join(weatherdata, by=c("Drug_origin"="countryname", "month"="MONTH","year"="YEAR"))%>%
                   select(GTD.gname, date, year, month, traffic, Harvest1:Harvest4, opium_t, opium_pr,everything()) %>% 
                   arrange(-traffic,GTD.gname,year,month)


mydata<-mydata %>% mutate(h1_date=ymd(paste(year,Harvest1,"01")),h2_date=ymd(paste(year,Harvest2,"01")),h3_date=ymd(paste(year,Harvest3,"01")),h4_date=ymd(paste(year,Harvest4,"01")))  %>%
  select(GTD.gname, date, year, month, traffic, Harvest1:Harvest4, h1_date,h2_date,h3_date,h4_date,entry_date,everything())

mydata$h1_date[is.na(mydata$Harvest1)]<-NA
mydata$h2_date[is.na(mydata$Harvest2)]<-NA
mydata$h3_date[is.na(mydata$Harvest3)]<-NA
mydata$h4_date[is.na(mydata$Harvest4)]<-NA

mydata <-mydata %>%
  mutate(d1=date-h1_date,d2=date-h2_date,d3=date-h3_date,d4=date-h4_date,d5=date-entry_date) %>%
  rowwise() %>% mutate(mo_since_harv=min(d1[d1>=0],d2[d2>=0],d3[d3>=0],d4[d4>=0],d5[d5>=0],na.rm=T))%>%
  select(GTD.gname, date, year, month, traffic, Harvest1:Harvest4, h1_date,h2_date,h3_date,h4_date,entry_date,d1:d5,mo_since_harv,everything())

mydata$mo_since_harv<-time_length(mydata$mo_since_harv,"month")
mydata$mo_since_harv<-round(mydata$mo_since_harv)
mydata$mo_since_harv[mydata$traffic==1]<-mydata$mo_since_harv[mydata$traffic==1]+1 #code the month of harvest as 1, to be distinct from non-trafficking groups which are 0
mydata$mo_since_harv[mydata$traffic==0]<- 0 #non-trafficking groups as 0




#Code temperature vars: 
#mydata<-mydata %>% filter( !is.na(ave_mo_t))

mydata$mo_harvest=as.numeric(mydata$month==mydata$Harvest1 | mydata$month==mydata$Harvest2 | mydata$month==mydata$Harvest3 | mydata$month==mydata$Harvest4)
mydata$mo_harvest<-replace_na(mydata$mo_harvest,0)
mydata<-mydata %>% select(GTD.gname, date, year, month, traffic, Harvest1:Harvest4, h1_date,h2_date,h3_date,h4_date,entry_date,d1:d5,mo_since_harv,mo_harvest,everything())
mydata$favtemp<-0
mydata$fav_pr<-0
mydata[mydata$Drug1=="Opium" & mydata$mo_harvest==1,]<- mydata[mydata$Drug1=="Opium" & mydata$mo_harvest==1,] %>% mutate(favtemp=opium_t, fav_pr=opium_pr) 

mydata[mydata$Drug1=="Cocaine" & mydata$mo_harvest==1,]<- mydata[mydata$Drug1=="Cocaine" & mydata$mo_harvest==1,] %>% mutate(favtemp=coca_t, fav_pr=coca_pr)

mydata[mydata$Drug1=="Marijuana" & mydata$mo_harvest==1,]<- mydata[mydata$Drug1=="Marijuana" & mydata$mo_harvest==1,] %>% mutate(favtemp=mj_t, fav_pr=mj_pr) 

mydata <- mydata %>% group_by(GTD.gname) %>% mutate(harv_num=cumsum(mo_harvest)) %>% select(GTD.gname, date, year, month, traffic, Harvest1:Harvest4, h1_date,h2_date,h3_date,h4_date,entry_date,d1:d5,mo_since_harv,mo_harvest,harv_num,everything())

mydata[mydata$traffic==1,]<-mydata[mydata$traffic==1,]  %>% 
  group_by(GTD.gname,harv_num) %>%
  fill(favtemp, fav_pr) %>% ungroup  

mydata[mydata$traffic==0,] <- mydata[mydata$traffic==0,] %>% mutate(favtemp=0,fav_pr=0) %>% arrange(-traffic, GTD.gname, date)

mydata<-mydata %>% group_by(GTD.gname) %>%
mutate(lead.mo = lead(mo_harvest, order_by=harv_num), mo_before_harv=as.numeric(lead.mo==1 & mo_harvest==0)) %>% arrange(-traffic,GTD.gname,year,month) %>% select(GTD.gname, date, year, month, traffic, Harvest1:Harvest4, mo_harvest, mo_since_harv,harv_num,lead.mo,mo_before_harv,everything()) %>%
  select(-d1,-d2,-d3,-d4,-d5)
#if harvest is two months, code month_before as just one

#write.csv(mydata, "terrdata.csv", row.names=FALSE)

```


#Control variables
```{r}
#CINC merge
CINC<-read.csv("NMC_5_0.csv")
mydata<-left_join(mydata,CINC, by=c("ccode", "year"))

##Polity data merge
polity<-read.csv("p4_v2017.csv")
mydata<-mydata %>% left_join(polity, by=c("ccode", "year"))

mydata$democracy<-0
mydata$democracy[mydata$polity2>=7]<-1

write.csv(mydata, "terr_data.csv")

```


